import json
from pathlib import Path


def write_json_report(ioc_data: dict, output_path: Path) -> None:
    """
    Write extracted IOCs to a JSON file.
    """
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(ioc_data, f, indent=4)


def build_markdown_report(ioc_data: dict, source_file: str) -> str:
    """
    Build a markdown report from extracted IOC data.
    """
    total_iocs = sum(len(values) for values in ioc_data.values())

    lines = [
        "# IOC Extraction Report",
        "",
        f"**Source File:** `{source_file}`",
        "",
        f"**Total IOCs Found:** {total_iocs}",
        "",
        "## Summary",
        "",
    ]

    for ioc_type, values in ioc_data.items():
        lines.append(f"- **{ioc_type.upper()}**: {len(values)}")

    lines.extend([
        "",
        "## Extracted IOCs",
        "",
    ])

    for ioc_type, values in ioc_data.items():
        lines.append(f"### {ioc_type.upper()}")
        if values:
            for value in values:
                lines.append(f"- `{value}`")
        else:
            lines.append("- None found")
        lines.append("")

    lines.extend([
        "## Analyst Notes",
        "",
        "- This report was automatically generated by the IOC Hunt Pack Generator.",
        "- Extracted values should be manually reviewed before operational use.",
        "",
    ])

    return "\n".join(lines)


def write_markdown_report(markdown_text: str, output_path: Path) -> None:
    """
    Write markdown report text to a file.
    """
    output_path.write_text(markdown_text, encoding="utf-8")